# Generated by Django 4.2.3 on 2023-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='fulfilment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
