# Generated by Django 4.2.3 on 2023-11-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_historicalperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='acknowledgment_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quality_rating',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
    ]
